apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-reader
  template:
    metadata:
      labels:
        app: message-reader
    spec:
      containers:
        - name: reader
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo Message: $(cat /config/message); sleep 3600"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: my-message-config
