kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: take-ownership-test
spec:
  repo: https://github.com/sbulage/test-fleet
  branch: main
  paths:
  - keep-resources/take-ownership
  targetNamespace: keep-resources
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
