apiVersion: batch/v1
kind: Job
metadata:
  name: preinstall-hang
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: hang
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
      restartPolicy: Never
