apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrdresources.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: mycrdresources
    singular: mycrdresource
    kind: MyCRDResource
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
