apiVersion: v2
name: guestbook-deps-simple
description: Sample application
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - name: sleeper-chart
    version: "0.2.0"
    repository: "https://github.com/rancher/fleet/tree/main/e2e/assets/helmop/sleeper-chart2"
#- name: postgresql
  # version: "13.4.3"
  #version: "18.5.8"
  #repository: "https://charts.bitnami.com/bitnami"
