apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-wait-job
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: alpine
        image: alpine
        command: ["echo", "hello world"]
